version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: songo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: songo_db
      MYSQL_USER: songo_user
      MYSQL_PASSWORD: songo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - songo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: songo-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: songo_user
      PMA_PASSWORD: songo_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - songo-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: songo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - songo-network
    command: redis-server --appendonly yes

  # Mailhog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: songo-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - songo-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  songo-network:
    driver: bridge
