server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: songo-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/songo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: songo_user
    password: songo_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always
      
  security:
    user:
      name: admin
      password: admin123
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:songoSecretKeyForJWTTokenGenerationAndValidation2024!@#$%^&*()}
  expiration: 86400000 # 24 hours in milliseconds

# Carrier API Configuration
carriers:
  canada-post:
    api-url: https://ct.soa-gw.canadapost.ca
    username: ${CANADA_POST_USERNAME:}
    password: ${CANADA_POST_PASSWORD:}
    customer-number: ${CANADA_POST_CUSTOMER_NUMBER:}
    
  purolator:
    api-url: https://devwebservices.purolator.com
    key: ${PUROLATOR_KEY:}
    password: ${PUROLATOR_PASSWORD:}
    account: ${PUROLATOR_ACCOUNT:}
    
  ups:
    api-url: https://wwwcie.ups.com
    username: ${UPS_USERNAME:}
    password: ${UPS_PASSWORD:}
    access-key: ${UPS_ACCESS_KEY:}
    
  fedex:
    api-url: https://wsbeta.fedex.com
    key: ${FEDEX_KEY:}
    password: ${FEDEX_PASSWORD:}
    account: ${FEDEX_ACCOUNT:}
    meter: ${FEDEX_METER:}

# Logging
logging:
  level:
    com.songo: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/songo-backend.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
